services:
  backend:
    build: .
    ports:
      - "5005:5000"
    depends_on:
      - db
      - notificaciones
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/usuarios


  db:
    image: postgres:15
    environment:
      POSTGRES_DB: usuarios
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  notificaciones:
    image: notificaciones:1.0
    ports:
      - "5001:5000"

